#!/bin/sh
set -eu

output=$(mktemp)
trap 'rm -f "$output"' EXIT HUP INT TERM

cat >"$output" <<EOF
[
  {
    "id": "example-$(date +%Y%m%d-%H%M)",
    "text": "Generated by feedr-node at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  }
]
EOF

feedr publish "$output"
